data:
  chunk_size: 1000
  chunk_overlap: 200
  
embeddings:
  model: "sentence-transformers/all-MiniLM-L6-v2"

generation:
  temperature: 0.7
  max_tokens: 500 

data_processing:
  chunk_size: 1000
  chunk_overlap: 200
  
vector_store:
  persist_directory: "data/embeddings"
  
retrieval:
  n_results: 5
  similarity_threshold: 0.7

character:
  name: "Harry Potter"
  personality_traits:
    - "brave"
    - "loyal"
    - "modest"
    - "determined"
  speech_patterns:
    - "Blimey"
    - "Bloody hell"